image:https://img.shields.io/github/workflow/status/loicrouchon/symly/Build?logo=GitHub&style=for-the-badge[Build, link="https://github.com/loicrouchon/symly/actions?query=workflow%3A%22Build%22"]
image:https://img.shields.io/github/workflow/status/loicrouchon/symly/CodeQL?logo=GitHub&style=for-the-badge&label=CodeQL[CodeQL, link="https://github.com/loicrouchon/symly/actions?query=workflow%3A%22CodeQL%22"]
image:https://img.shields.io/github/license/loicrouchon/symly?style=for-the-badge&logo=apache[License, link="https://github.com/loicrouchon/symly/blob/main/LICENSE"]
image:https://img.shields.io/github/languages/code-size/loicrouchon/symly?logo=java&style=for-the-badge[Code Size, link="https://github.com/loicrouchon/symly/archive/refs/heads/main.zip"]

== Symly, centralize sparse file trees

Symly is a tool helping to centralize sparse file trees.
It replicates and maintains a file tree structure of one or multiple `repository` layers into a `directory` by creating symbolic links.

* *Layers*: Symly supports the definition of multiple repositories which will be combined in an overriding fashion similar to what is by https://en.wikipedia.org/wiki/OverlayFS[OverlayFS].
* *No database*: the filesystem is the state
* *Backup, Sharing and Synchronization tool of your choice*: Symly replicates the file tree of the repositories inside another file tree using symbolic links.
 But it doesn't provide a way to share, synchronize, backup, ... the repositories content.
 You can then decide to use one or more tools of your choice for this task: git, rsync, Dropbox, Tresorit, ...

=== Common use cases

* dotfiles management
* Application installation

=== Getting started

* link:./docs/what-is-symly-useful-for.adoc[What is symly useful for?]
* link:./docs/install.adoc[Installation]
* link:./docs/concepts.adoc[Concepts]
* link:./docs/usage.adoc[Usage]
* link:./docs/features.adoc[Features and roadmap]

=== How to build Symly

The build instructions are available one the link:./docs/build.adoc[build instructions] page.
