[versions]
picocli = "4.7.1"
junit = "5.9.2"

[libraries]

errorprone = "com.google.errorprone:error_prone_core:2.18.0"

picocli-core = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
