= Usage

General command help:

// include::docs/snippets/symly-default-output.adoc[]
----
$ symly
Usage: symly [-hvV] [COMMAND]
symly create links
  -h, --help      Prints this help message and exits
  -v, --verbose   Be verbose.
  -V, --version   Prints version information.
Commands:
  link, ln    Create/update/delete links from 'directory' to the 'repositories'.

              Repositories should be specified with base layers first and
                overriding layers next.In case two repositories contain a file
                with the same path, the file in the latestrepository will be
                used as the target for the link for the given path
  status, st  Displays the current synchronization status
  unlink      Remove links in 'directory' pointing to the 'repositories'
----
// end::include

== The `link` subcommand

The `link` subcommand is the main subcommand that will perform the linking.

// include::docs/snippets/symly-link-help.adoc[]
----
$ symly link --help
Usage: symly link [-fhv] [--dry-run] [-d=<main-directory>]
                  [--max-depth=<max-depth>] [-r[=<repositories>...]]...
Create/update/delete links from 'directory' to the 'repositories'.

Repositories should be specified with base layers first and overriding layers
next.In case two repositories contain a file with the same path, the file in
the latestrepository will be used as the target for the link for the given path
  -d, --dir, --directory=<main-directory>
                  Main directory in which links will be created
      --dry-run   Do not actually create links but only displays which ones
                    would be created
  -f, --force     Force existing files and directories to be overwritten
                    instead of failing in case of conflicts
  -h, --help      Prints this help message and exits
      --max-depth=<max-depth>
                  Depth of the lookup for orphans deletion
  -r, --repositories[=<repositories>...]
                  Repositories containing files to link in the main directory.
                    Repositories are to be listed by decreasing priority as the
                    first ones will override the content of the later ones.
  -v, --verbose   Be verbose.
----
// end::include

* Links every file from the `repositories` into the `main directory` by preserving the structure.

// include::docs/snippets/symly-link-basic-example.adoc[]
----
$ tree /home/user
/home/user:
\-- repository/
    |-- .bashrc
    |-- .config/
    |   |-- fish/
    |   |   \-- config.fish
    |   \-- starship.toml
    \-- .gitconfig

$ symly link --dir ~ --repositories repository
added:       .bashrc -> /home/user/repository/.bashrc
added:       .config/fish/config.fish -> /home/user/repository/.config/fish/config.fish
added:       .config/starship.toml -> /home/user/repository/.config/starship.toml
added:       .gitconfig -> /home/user/repository/.gitconfig

$ tree /home/user
/home/user:
|-- .bashrc -> /home/user/repository/.bashrc
|-- .config/
|   |-- fish/
|   |   \-- config.fish -> /home/user/repository/.config/fish/config.fish
|   \-- starship.toml -> /home/user/repository/.config/starship.toml
|-- .gitconfig -> /home/user/repository/.gitconfig
\-- repository/
    |-- .bashrc
    |-- .config/
    |   |-- fish/
    |   |   \-- config.fish
    |   \-- starship.toml
    \-- .gitconfig
----
// end::include
* Supports multiple `repositories`: Repositories are listed by increasing order of priority (default first, overrides last).
When two repositories define a link, the link will be created to the repository with the higher priority.

// include::docs/snippets/symly-link-multiple-repositories-example.adoc[]
----
$ tree /home/user
/home/user:
\-- repositories/
    |-- custom/
    |   \-- .bashrc
    \-- defaults/
        |-- .config/
        |   \-- starship.toml
        \-- .gitconfig

$ symly link --dir ~ --repositories repositories/defaults repositories/custom
added:       .bashrc -> /home/user/repositories/custom/.bashrc
added:       .config/starship.toml -> /home/user/repositories/defaults/.config/starship.toml
added:       .gitconfig -> /home/user/repositories/defaults/.gitconfig

$ touch repositories/custom/.gitconfig

$ symly link --dir ~ --repositories repositories/defaults repositories/custom
deleted:     .gitconfig -> /home/user/repositories/defaults/.gitconfig
added:       .gitconfig -> /home/user/repositories/custom/.gitconfig
----
// end::include

* Supports directory linking when a `.symlink` file is present in the directory.

// include::docs/snippets/symly-link-directory-linking-example.adoc[]
----
$ tree /home/user
/home/user:
\-- repository/
    \-- .config/
        \-- fish/
            |-- .symlink
            \-- config.fish

$ symly link --dir ~ --repositories repository
added:       .config/fish -> /home/user/repository/.config/fish
----
// end::include

== The symly.config file

It might be annoying to keep giving the `--dir` and `--repositories` options, even when using the short names.
To this end, it is possible to define a `symly.config` file that will automatically be picked up by symly.

_For the file to be detected by symly, it needs to be present in the current working directory._

The following entries are supported:

* `directory`: the main directory.
* `repositories`: the list of repositories, separated by a `,`.
* `orphans.max-depth.search`: the max depth to look-up for orphan links.

For example:

[source,properties]
----
directory=~
repositories=defaults, linux, work
----

Paths defined in this file can be:

* absolute paths.
* relative to the user directory when starting with `~`.
* relative to the file parent directory.
