= Usage

General command help:

----
Usage: symly [-hvV] [COMMAND]
symly create links
  -h, --help      Prints this help message and exits
  -v, --verbose   Be verbose.
  -V, --version   Prints version information.
Commands:
  link, ln    Create/update links from 'directory' to the 'to' repositories
  status, st  Displays the current synchronization status
  unlink      Remove links in 'directory' pointing to the 'to' repositories
----

== The `link` subcommand

The `link` subcommand is the main subcommand that will perform the linking.

----
Usage: symly link [-f] [--dry-run] [-d=<main-directory>]
                  [--max-depth=<max-depth>] -r=<repositories>...
                  [-r=<repositories>...]...
Create/update links from 'directory' to the 'to' repositories
  -d, --dir, --directory=<main-directory>
                  Main directory in which links will be created
                    Default: $HOME
      --dry-run   Do not actually create links but only displays which ones
                    would be created
  -f, --force     Force existing files and directories to be overwritten
                    instead of failing in case of conflicts
      --max-depth=<max-depth>
                  Depth of the lookup for orphans deletion
  -r, --repositories=<repositories>...
                  Repositories containing files to link in the main directory
----

* Links every file from the `repositories` into the `main directory` by preserving the structure.

----
$ tree ~/my/repository
~/my/repository
 |-- .bashrc
 |-- .gitconfig
 >-- .config
     |-- starship.toml
     >-- fish
         |-- config.fish

$ symly link --dir ~ --repositories ~/my/repository

added:      .bashrc -> ~/my/repository/.bashrc
added:      .gitconfig -> ~/my/repository/.gitconfig
added:      .config/starship.toml -> ~/my/repository/.config/starship.toml
added:      .config/fish/config.fish -> ~/my/repository/.config/fish/config.fish
----

* Supports multiple `repositories`: Repositories are listed by increasing order of priority (default first, overrides last).
When two repositories define a link, the link will be created to the repository with the higher priority.

----
$ tree ~/my/repositories
~/my/repositories
 |-- custom
 |   >-- .bashrc
 >-- defaults
     |-- .gitconfig
     >-- .config
        >-- starship.toml


$ symly link --dir ~ --repositories ~/my/repositories/defaults ~/my/repositories/custom

added:      .bashrc -> ~/my/repositories/custom/.bashrc
added:      .gitconfig -> ~/my/repositories/default/.gitconfig
added:      .config/starship.toml -> ~/my/repositories/defaults/.config/starship.toml

$ echo "Let's override the default .gitconfig and see how symly reacts"

$ touch ~/my/repositories/custom/.gitconfig

$ symly link --dir ~ --repositories ~/my/repositories/defaults ~/my/repositories/custom

deleted:    .gitconfig -> ~/my/repositories/default/.gitconfig
added:      .gitconfig -> ~/my/repositories/custom/.gitconfig
----

* Supports directory linking when a `.symlink` file is present in the directory.

----
$ tree ~/my/repository
~/my/repository
 >-- .config
     >-- fish
         |-- .symlink
         >-- config.fish

$ symly link  --dir ~ --repositories ~/my/repository

added:      ~/.config/fish -> ~/my/repository/.config/fish
----

== The symly.config file

It might be annoying to keep giving the `--dir` and `--repositories` options, even when using the short names.
To this end, it is possible to define a `symly.config` file that will automatically be picked up by symly.

_For the file to be detected by symly, it needs to be present in the current working directory._

The following entries are supported:

* `directory`: the main directory.
* `repositories`: the list of repositories, separated by a `,`.
* `orphans.max-depth.search`: the max depth to look-up for orphan links.

For example:

[source,properties]
----
directory=~
repositories=defaults, linux, work
----

Paths defined in this file can be:

* absolute paths.
* relative to the user directory when starting with `~`.
* relative to the file parent directory.
